@startuml

class Empleado{
    cedula: string
    nombres: string
    apellidos: string
    genero: string

    + pagarSueldo(comision): number
    - calcularSeguro()
    # registrarAsistencia()
}
class PuestoTrabajo{
    area: string
    departamento: string
}
class Empresa{
    ruc: string
    nombre: string
    direccion: string
    telefono: string
}
class Estudiante{
    identificacion: string
    numeroMatricula: string
    nombres: string
    apellidos: string
    edad: number
}
class Materia{
    codigo: string
    nombre: string
    horas: string
    area: String
}
class Profesor{
    cedula: string
    nombres: string
    apellidos: string
    edad: number
}
class Escuela{
    numero: string
    nombre: string
    direccion: string
}
class Universidad{
    numero: string
    nombre: string
    cantidadCarreras: number
    direccion: string
}
class Vehiculo{
    placa: string
    marca: string
    color: string
    numeroMotor: String
}

@enduml
